[project]
id = "your-project-id"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[auth]
site_url = "littlejourney://"
additional_redirect_urls = ["littlejourney://", "http://localhost:8081"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.apple]
enabled = false
client_id = ""
secret = ""

[storage]
file_size_limit = "50MiB"

[realtime]
enabled = true
