import React, { useMemo, useState } from 'react';
import {
  View, Text, StyleSheet, FlatList, TouchableOpacity, Alert, ActivityIndicator,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Colors, Shadows, BorderRadius, Spacing, FontSizes } from '../../theme/colors';
import { useApp } from '../../context/AppContext';

type AdminNavigation = { navigate: (screen: string) => void; goBack: () => void };

type SummaryCard = {
  key: string;
  icon: keyof typeof Ionicons.glyphMap;
  label: string;
  value: number;
  tint: string;
};

export const GenerateReportScreen = ({ navigation }: { navigation?: AdminNavigation }) => {
  const { children, attendance, timelineEntries } = useApp();
  const [isExporting, setIsExporting] = useState(false);

  // ── Derive an honest summary from data already in context ──
  const summary = useMemo(() => {
    const totalChildren = children.length;

    const present = attendance.filter((a) => a.status === 'present').length;
    const late = attendance.filter((a) => a.status === 'late').length;
    const absent = attendance.filter((a) => a.status === 'absent').length;
    const excused = attendance.filter((a) => a.status === 'excused').length;

    const today = new Date().toDateString();
    const activitiesToday = timelineEntries.filter(
      (e) => new Date(e.timestamp).toDateString() === today
    ).length;

    return { totalChildren, present, late, absent, excused, activitiesToday };
  }, [children, attendance, timelineEntries]);

  const cards: SummaryCard[] = [
    { key: 'enrolled', icon: 'people', label: 'Children Enrolled', value: summary.totalChildren, tint: Colors.primary },
    { key: 'present', icon: 'checkmark-circle', label: 'Present', value: summary.present, tint: Colors.success },
    { key: 'late', icon: 'time', label: 'Late', value: summary.late, tint: Colors.warning },
    { key: 'absent', icon: 'close-circle', label: 'Absent', value: summary.absent, tint: Colors.danger },
    { key: 'excused', icon: 'document-text', label: 'Excused', value: summary.excused, tint: Colors.secondary },
    { key: 'activities', icon: 'sparkles', label: "Today's Activities", value: summary.activitiesToday, tint: Colors.primary },
  ];

  const reportDate = useMemo(
    () => new Date().toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }),
    []
  );

  const handleExportPdf = async () => {
    setIsExporting(true);
    const html = `
      <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 32px; color: #333; }
          h1 { color: #6C63FF; margin-bottom: 4px; }
          .date { color: #888; font-size: 14px; margin-bottom: 20px; }
          h2 { color: #555; font-size: 16px; margin-top: 24px; border-bottom: 1px solid #eee; padding-bottom: 6px; }
          .stats { display: flex; flex-wrap: wrap; gap: 12px; margin: 16px 0; }
          .stat { background: #f5f5ff; border-radius: 8px; padding: 12px 16px; text-align: center; flex: 1; min-width: 100px; }
          .stat-value { font-size: 22px; font-weight: 800; color: #6C63FF; }
          .stat-label { font-size: 11px; color: #888; margin-top: 2px; }
          .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #eee; color: #aaa; font-size: 12px; text-align: center; }
        </style>
      </head>
      <body>
        <h1>Daycare Summary Report</h1>
        <div class="date">${reportDate}</div>

        <h2>Enrollment</h2>
        <div class="stats">
          <div class="stat"><div class="stat-value">${summary.totalChildren}</div><div class="stat-label">Children Enrolled</div></div>
        </div>

        <h2>Today's Attendance</h2>
        <div class="stats">
          <div class="stat"><div class="stat-value">${summary.present}</div><div class="stat-label">Present</div></div>
          <div class="stat"><div class="stat-value">${summary.late}</div><div class="stat-label">Late</div></div>
          <div class="stat"><div class="stat-value">${summary.absent}</div><div class="stat-label">Absent</div></div>
          <div class="stat"><div class="stat-value">${summary.excused}</div><div class="stat-label">Excused</div></div>
        </div>

        <h2>Activity</h2>
        <div class="stats">
          <div class="stat"><div class="stat-value">${summary.activitiesToday}</div><div class="stat-label">Activity Entries Today</div></div>
        </div>

        <div class="footer">Generated by Little Journey &bull; ${reportDate}</div>
      </body>
      </html>
    `;
    try {
      const { uri } = await Print.printToFileAsync({ html });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Daycare Summary Report' });
      } else {
        Alert.alert('PDF Saved', `Report saved to: ${uri}`);
      }
    } catch (err) {
      console.warn('[GenerateReport] PDF export failed:', err);
      Alert.alert('Export Failed', 'We could not generate the PDF report. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <View style={styles.container}>
      <LinearGradient colors={['#6C63FF', '#3F3D9E']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 1 }} style={styles.header}>
        <View style={styles.headerRow}>
          {navigation && (
            <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
              <Ionicons name="arrow-back" size={24} color={Colors.white} />
            </TouchableOpacity>
          )}
          <Text style={styles.headerTitle}>Generate Report</Text>
        </View>
        <Text style={styles.headerMeta}>{reportDate}</Text>
      </LinearGradient>

      <FlatList
        data={cards}
        keyExtractor={(item) => item.key}
        numColumns={2}
        columnWrapperStyle={styles.row}
        contentContainerStyle={styles.list}
        showsVerticalScrollIndicator={false}
        ListHeaderComponent={
          <Text style={styles.sectionLabel}>Summary</Text>
        }
        renderItem={({ item }) => (
          <View style={[styles.card, Shadows.small]}>
            <View style={[styles.iconCircle, { backgroundColor: item.tint + '20' }]}>
              <Ionicons name={item.icon} size={22} color={item.tint} />
            </View>
            <Text style={styles.cardValue}>{item.value}</Text>
            <Text style={styles.cardLabel}>{item.label}</Text>
          </View>
        )}
        ListFooterComponent={
          <TouchableOpacity style={styles.exportBtn} onPress={handleExportPdf} disabled={isExporting}>
            <LinearGradient colors={['#6C63FF', '#3F3D9E']} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }} style={styles.exportGradient}>
              {isExporting ? (
                <ActivityIndicator color={Colors.white} />
              ) : (
                <>
                  <Ionicons name="download-outline" size={20} color={Colors.white} />
                  <Text style={styles.exportText}>Export PDF</Text>
                </>
              )}
            </LinearGradient>
          </TouchableOpacity>
        }
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { paddingTop: 60, paddingBottom: Spacing.lg, paddingHorizontal: Spacing.lg, borderBottomLeftRadius: BorderRadius.xl, borderBottomRightRadius: BorderRadius.xl },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  backBtn: { padding: Spacing.xs },
  headerTitle: { fontSize: FontSizes.xxl, color: Colors.white, fontWeight: '800' },
  headerMeta: { fontSize: FontSizes.sm, color: 'rgba(255,255,255,0.7)', marginTop: Spacing.xs },
  list: { padding: Spacing.lg, paddingBottom: 100 },
  sectionLabel: { fontSize: FontSizes.sm, fontWeight: '600', color: Colors.textMuted, textTransform: 'uppercase', marginBottom: Spacing.md },
  row: { gap: Spacing.md, marginBottom: Spacing.md },
  card: { flex: 1, backgroundColor: Colors.card, borderRadius: BorderRadius.lg, padding: Spacing.lg, alignItems: 'center' },
  iconCircle: { width: 44, height: 44, borderRadius: 22, justifyContent: 'center', alignItems: 'center', marginBottom: Spacing.sm },
  cardValue: { fontSize: FontSizes.xxl, fontWeight: '800', color: Colors.textPrimary },
  cardLabel: { fontSize: FontSizes.sm, color: Colors.textMuted, marginTop: 2, textAlign: 'center' },
  exportBtn: { marginTop: Spacing.lg, borderRadius: BorderRadius.lg, overflow: 'hidden' },
  exportGradient: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: Spacing.md, gap: Spacing.sm },
  exportText: { fontSize: FontSizes.lg, color: Colors.white, fontWeight: '700' },
});
